<?php
/**
 * BibleBridge v1.5 - Configuration File
 * This file is automatically generated by the setup script.
 * * If you are seeing this, please run yourdomain.com/setup.php
 * to initialize your database connection.
 */
?>